/** Declaration file generated by dts-gen */

export class SchemaRegistryAvroFetcher {
    constructor(...args: any[]);
    fetchAvro(...args: any[]): void;
    isCompatible(...args: any[]): void;
}

export function javro(options: any): any;
